### ISSUE TITLE
What is the goal of this query?

### ISSUE THREAD

**Issue by stephanieamrivera** [databricks-industry-solutions/anti-money-laundering#1]
Hi,

At [line 159](https://github.com/databricks-industry-solutions/anti-money-laundering/blob/15442ced998e7740fc4647545af939126285bf83/01_aml_network_analysis.py#L159), the type is being added back to the table via join that was just filtered out. Can someone help me understand what the goal here was? I don't know how to fix it without knowing what the goal was.

**Comment by stephanieamrivera** [comment]
I think the issue is the 'id' needs dropped in the join

**Comment by dbbnicole** [comment]
Hi authors @anindita-Databricks @rportilla-databricks: Are you familiar with the query on [line 159](https://github.com/databricks-industry-solutions/anti-money-laundering/blob/15442ced998e7740fc4647545af939126285bf83/01_aml_network_analysis.py#L159)?

**Comment by stephanieamrivera** [comment]
I fixed it in my PR
